/*CREATE DATABASE DOMOTICKS_UDATA;*/
USE DOMOTICKS_UDATA;

/*DROP SECTION*/
#DROP TRIGGER TRG_BI_USER_P_DATA;
#DROP TABLE T_USER_P_DATA;


CREATE TABLE T_USER_P_DATA(
PID INT AUTO_INCREMENT NOT NULL,
FNAME VARCHAR(100) NOT NULL,
LNAME VARCHAR(100) NOT NULL,
BDAY  DATE NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
LOCATION VARCHAR(50),
CREATED_AT DATETIME ,
CONSTRAINT PK_USER_P_DATA PRIMARY KEY (PID)
)COLLATE='utf8_bin';


CREATE OR REPLACE TRIGGER TRG_BI_USER_P_DATA
BEFORE INSERT ON T_USER_P_DATA
FOR EACH ROW 
UPDATE T_USER_P_DATA SET CREATED_AT = SYSDATE;

