/*CREATE DATABASE DOMOTICKS_UDATA;*/
USE DOMOTICKS_UDATA;

/*DROP SECTION*/
#DROP TRIGGER TRG_BI_USERDATA;
#DROP TABLE T_USERDATA;


CREATE TABLE T_USERDATA(
USERNAME VARCHAR(14) NOT NULL,
PSSWD VARCHAR(1000) NOT NULL,
USER_CODE INT AUTO_INCREMENT UNIQUE NOT NULL,
PID INT NOT NULL,
STATE VARCHAR(3) NOT NULL,
CREATED_AT DATETIME NOT NULL,
CONSTRAINT PK_USERDATA PRIMARY KEY (USERNAME),
CONSTRAINT FK_USERDATA_01 FOREIGN KEY (PID)
REFERENCES T_USER_P_DATA (PID),
CONSTRAINT CK_USERDATA_01 CHECK(STATE IN ('ACT','DIS'))
)COLLATE='utf8_bin';

CREATE OR REPLACE TRIGGER TRG_BI_USERDATA
BEFORE INSERT ON T_USERDATA
FOR EACH ROW 
UPDATE T_USERDATA SET CREATED_AT = SYSDATE, STATE = 'ACT';