/*CREATE DATABASE DOMOTICKS_UDATA;*/
USE DOMOTICKS_UDATA;

/*DROP SECTION*/
#DROP TABLE T_USERDATA;
#DROP TRIGGER TRG_BI_USERDATA;

CREATE TABLE T_USER_MOTICK(
ID_MOTICK INT AUTO_INCREMENT UNIQUE NOT NULL,
ASOCIATED_USER INT NOT NULL,
MOTICK_CODE VARCHAR(100) NOT NULL,
MOTICK_NAME VARCHAR(100) NOT NULL,
MOTICK_DESC VARCHAR(100) NOT NULL,
MOTICK_STATE VARCHAR(3) NOT NULL,
CREATED_AT DATETIME NOT NULL,
CONSTRAINT PK_USER_MOTICK PRIMARY KEY (ID_MOTICK),
CONSTRAINT FK_USER_MOTICK_01 FOREIGN KEY (ASOCIATED_USER)
REFERENCES T_USERDATA (USER_CODE),
CONSTRAINT CH_USER_MOTICK_01 CHECK (MOTICK_STATE IN ('ACT','DIS'))
)COLLATE='utf8_bin';

CREATE OR REPLACE TRIGGER TRG_BI_USERDATA
BEFORE INSERT ON T_USERDATA
FOR EACH ROW 
UPDATE T_USERDATA SET CREATED_AT = SYSDATE, MOTICK_STATE ='ACT';